name: cuco_health_challenge
description: A showcase app for Cuco Health interview, displaying user related info.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  connectivity_plus: 2.3.6+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_native_splash: 2.2.7
  flutter_dotenv: 5.0.2
  http: 0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
    - assets/images/

  uses-material-design: true

flutter_native_splash:
  color: "#FFC000"
  image: assets/splash/user_300x300.png
  android_12:
    color: "#FFC000"
    image: assets/splash/user_300x300.png






























